### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol 'setRecognizerScaleFactor': error code 127

### ISSUE THREAD

**Issue by vutung1671997** [alnitak/flutter_opencv_dlib#1]
i'm have trouble this issue when build example with windows platform

Full log:
flutter: AVAILABLE CAMERAS: 0  name: USB2.0 UVC HD Webcam <\\?\usb#vid_13d3&pid_5654&mi_00#6&3907f7b1&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global>   lensDirection: CameraLensDirection.front   sensorOrientation: 0
flutter: AVAILABLE CAMERAS: 1  name: Camo <\\?\root#camera#0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\{32b66cd3-5a83-4878-b90d-7bdca94e066b}>   lensDirection: CameraLensDirection.front   sensorOrientation: 0

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown attaching to the render tree:
Invalid argument(s): Failed to lookup symbol 'setRecognizerScaleFactor': error code 127

When the exception was thrown, this was the stack:
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      new RecognizerInterface._internal (package:flutter_opencv_dlib/src/recognizer_interface.dart:80:10)
#2      new RecognizerInterface (package:flutter_opencv_dlib/src/recognizer_interface.dart:68:39)
#3      _MyAppState.initState (package:flutter_opencv_dlib_example/main.dart:102:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
#10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111:18)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
#13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
#14     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════

Thanks !

**Comment by alnitak** [comment]
Hi,

only on Linux the camera is supported by now. The camera plugin, which is used for mobile, doesn't support desktop. For this reason there is the example/lib/main_desktop.dart which uses the OpenCV camera, but I have implemented this only for linux due to lack of knowledge on other OSes.
Since you are trying on Windows, I suggest you to look at _example/lib/main_desktop.dart_ and try to feed the DetectorInterface or RecognitionInterface with images instead, like in that example, with webcam frames

**Comment by vutung1671997** [comment]
>
