### ISSUE TITLE
Not a Bug just a stupid question from me

### ISSUE THREAD

**Issue by azkadev** [alnitak/flutter_opencv_dlib#2]
I plan to make face recognition to authenticate login apps,
so it will run server side and i plan to use dart,

Can it be run on dart using ffi?

Sorry I don't know where else to go, most of the tutorials use flutter

**Comment by alnitak** [comment]
Hi,

this plugin works using FFI and has been tested only on android and linux using camera frames to test it in real time. On linux simply be sure to have dlib and OpenCV libs installed.
If I remember well, you can pass raw images (as Uint8List) to it and have as result the recognized face accuracy.
Be aware that face login is not a secure method and this plugin is not made thinking on that!
