### ISSUE TITLE
Issue in deserialization

### ISSUE THREAD

**Issue by RahulFlutter225** [alnitak/flutter_opencv_dlib#3]
E/libc++abi: terminating with uncaught exception of type dlib::serialization_error: An error occurred while trying to read the first object from the stream.
ERROR: Error deserializing object of type int
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 26598 (DartWorker), pid 17743 (cv_dlib_example)

**Comment by alnitak** [comment]
Some more information on when you get the error, the code you have used, on which SO you received that and which device you are using, may help understand the problem!

**Comment by RahulFlutter225** [comment]
Well, thanks for replying
I am getting the above error when the app gets installed and preview the camera and then it ends up with the crash mentioned above.
System Used:- Mac Os 
Trying to install it on an Android device(Android Version=11) using Android studio.

Also, before this, I am getting stuck on this error while running the "buildDlib-android" following error is what I am getting
I think the main root cause is this error related to CMake
Any help would be highly appreciated.

Error :-

Android/Sdk/cmake/3.10.2.4988404/bin/cmake: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip: No such file or directory
flutter_opencv_dlib-main/BUILD_LIBS/buildDlib/libs-android/armeabi-v7a/lib/libdlib.so: No such file or directory

Android/Sdk/cmake/3.10.2.4988404/bin/cmake: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip: No such file or directory

flutter_opencv_dlib-main/BUILD_LIBS/buildDlib/libs-android/arm64-v8a/lib/libdlib.so: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/cmake: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip: No such file or directory


flutter_opencv_dlib-main/BUILD_LIBS/buildDlib/libs-android/x86_64/lib/libdlib.so: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/cmake: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/cmake/3.10.2.4988404/bin/ninja: No such file or directory
Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip: No such file or directory
flutter_opencv_dlib-main/BUILD_LIBS/buildDlib/libs-android/x86/lib/libdlib.so: No such file or directory
flutter_opencv_dlib-main/BUILD_LIBS/buildDlib/libs-android/arm64-v8a/include: No such file or directory


if (all is gone well)
{
    dlib has been installed in android/src/main/dlib
    &
    you can delete './build-dlib-android' dir!
    you can delete './dlib' dir!
    you can delete './libs-android' dir!
printf%                                                                                                                                             eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeessm@192 buildDlib %

**Comment by alnitak** [comment]
this plugin is working on linux and android. Unfortunately I don't have a mac and that script is working on linux (there is also a windows script), but I think that with little modification or maybe no modification, it could work also work on a mac.
I think the problem is, like you noticed, that your system doesn't have installed cmake and ninja. 
If I recall correctly, on mac there is the "brew" tool to install packages, you can try to search for that. With something similar to
```brew install ninja```
maybe you can resolve but I can't help you more compiling on a mac, sorry.

**Comment by RahulFlutter225** [comment]
Okay, but I was also trying to install the app through the windows system but getting similar error
Error:-

Build fingerprint: 'Redmi/lime_in/lime:11/RKQ1.201004.002/V12.5.9.0.RJQINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-03-10 17:51:38+0530
pid: 9601, tid: 10080, name: DartWorker  >>> com.bavagnoli.flutter_opencv_dlib_example <<<
uid: 10470
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'terminating with uncaught exception of type dlib::serialization_error: An error occurred while trying to read the first object from the stream.
ERROR: Error deserializing object of type int
'
    x0  0000000000000000  x1  0000000000002760  x2  0000000000000006  x3  000000777d7f4210
    x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  76092d7851c192f2  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 20656874206d6f72  x14 000000780b4c2be2  x15 0000000000040000
    x16 000000780b4be948  x17 000000780b49d3d0  x18 00000077775c6000  x19 0000000000002581
    x20 0000000000002760  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 000000777d7f4460
    x24 000000777d7f4340  x25 000000777d7f4380  x26 b40000777a556600  x27 0000007605d49090
    x28 0000000800000076  x29 000000777d7f4290
    lr  000000780b450ae0  sp  000000777d7f41f0  pc  000000780b450b0c  pst 0000000000000000
backtrace:
      #00 pc 0000000000089b0c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 2b2492e95837f9311f775b9b44b07332)
      #01 pc 000000000009ce88  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libc++_shared.so (abort_message+236) (BuildId: ece72a2ebc3774a1be9fd21271258acd3bcdfaa7)
      #02 pc 000000000009d07c  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libc++_shared.so (demangling_terminate_handler()+260) (BuildId: ece72a2ebc3774a1be9fd21271258acd3bcdfaa7)
      #03 pc 00000000000aead0  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libc++_shared.so (std::__terminate(void (*)())+12) (BuildId: ece72a2ebc3774a1be9fd21271258acd3bcdfaa7)
      #04 pc 00000000000ae0fc  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libc++_shared.so (__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)+28) (BuildId: ece72a2ebc3774a1be9fd21271258acd3bcdfaa7)
      #05 pc 00000000000ae058  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libc++_shared.so (__cxa_throw+112) (BuildId: ece72a2ebc3774a1be9fd21271258acd3bcdfaa7)
      #06 pc 0000000001edfd54  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libflutter_opencv_dlib_plugin.so (dlib::proxy_deserialize& dlib::proxy_deserialize::doit<dlib::shape_predictor&>(dlib::shape_predictor&)+788) (BuildId: b4161eb04ab3d3cce40a0a00e152ecae5c3ca27a)
      #07 pc 0000000001e9dac4  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libflutter_opencv_dlib_plugin.so (dlib::proxy_deserialize& dlib::proxy_deserialize::operator>><dlib::shape_predictor>(dlib::shape_predictor&)+28) (BuildId: b4161eb04ab3d3cce40a0a00e152ecae5c3ca27a)
      #08 pc 0000000001f3be14  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libflutter_opencv_dlib_plugin.so (FaceRecognition::initFaceRecognition(char*, long, char*, long)+168) (BuildId: b4161eb04ab3d3cce40a0a00e152ecae5c3ca27a)
      #09 pc 0000000001e95568  /data/app/~~TZQUjNdXzQ1xgMlWaJGebA==/com.bavagnoli.flutter_opencv_dlib_example-iIhd183zaQxfFPCYacoIVw==/lib/arm64/libflutter_opencv_dlib_plugin.so (initRecognition+88) (BuildId: b4161eb04ab3d3cce40a0a00e152ecae5c3ca27a)
      #10 pc 0000000000006f64  [anon:dart-code]

**Comment by alnitak** [comment]
Something strange happened!
I tried to clone this repo an I got the same error you described, while on my local source I didn't.
I seen a file used by dlib wasn't uploaded correctly into GitHub because I used git-lfs for large files which was the cause of the wrong file uploaded.
The file is named ```shape_predictor_5_face_landmarks.dat``` and it is 9.7Mb in the assets folder.

I have updated the project, please try it and let me know if it is working now

**Comment by RahulFlutter225** [comment]
Hi,
No still the same error is coming i have tried it even on the windows os.

**Comment by alnitak** [comment]
Hi @RahulFlutter225 ,

I checked now and the ```assets/shape_predictor_5_face_landmarks.dat``` file is still 132 bytes instead of 9.7Mb! I don't know yet why, but meanwhile you can download that from here: 
[https://github.com/davisking/dlib-models](https://github.com/davisking/dlib-models)
and replace it.

I will try to fix the repo later.

**Comment by alnitak** [comment]
I had to rename that file because it was stored to be into git lfs. Now the repo should be working. If not, please reopen this issue.

**Comment by RahulFlutter225** [comment]
Yes, its working. Thanks!
