### ISSUE TITLE
When debugging mode is very slow on getFacePosePointsIsolate() Function , can this problem be solved or using open gpu to detect ?

### ISSUE THREAD

**Issue by iop04329** [alnitak/flutter_opencv_dlib#4]
Thanks for excellent project !
Very very useful .
I want to ask for debugging mode is very slow when i using usb to connect a android phone to detect,
is there any way to speed up, or the future would add the gpu version for test !
The slow location is at the  Future<FacePoints> getFacePosePointsIsolate(Map params) Function

```
Pointer<Int32> retFacePoints =
      getFacePosePoints(width, height, bytesPerPixel, buffer, retFaceCount);
```

**Comment by alnitak** [comment]
Hi, 
yes, in debug mode all compiler optimizations are disabled. I don't think there is a way to speed it up as in release mode.
[Here](http://dlib.net/faq.html#Whyisdlibslow) some more infos

But if you have any ideas please tell me!
